<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'CmsLayout\Exception\ExceptionInterface'                => __DIR__ . '/src/Exception/ExceptionInterface.php',
    'CmsLayout\Exception\InvalidArgumentException'          => __DIR__ . '/src/Exception/InvalidArgumentException.php',
    'CmsLayout\Exception\RuntimeException'                  => __DIR__ . '/src/Exception/RuntimeException.php',
    'CmsLayout\Factory\ModuleOptionsFactory'                => __DIR__ . '/src/Factory/ModuleOptionsFactory.php',
    'CmsLayout\Listener\Exception\InvalidArgumentException' => __DIR__ . '/src/Listener/Exception/InvalidArgumentException.php',
    'CmsLayout\Listener\Exception\RuntimeException'         => __DIR__ . '/src/Listener/Exception/RuntimeException.php',
    'CmsLayout\Listener\LayoutListener'                     => __DIR__ . '/src/Listener/LayoutListener.php',
    'CmsLayout\Module'                                      => __DIR__ . '/src/Module.php',
    'CmsLayout\Mvc\Controller\AdminController'              => __DIR__ . '/src/Mvc/Controller/AdminController.php',
    'CmsLayout\Options\ModuleOptions'                       => __DIR__ . '/src/Options/ModuleOptions.php',
    'CmsLayout\Options\ModuleOptionsInterface'              => __DIR__ . '/src/Options/ModuleOptionsInterface.php',
    'CmsLayoutTest\Framework\TestCase'                      => __DIR__ . '/tests/Framework/TestCase.php',
    'CmsLayoutTest\SampleTest'                              => __DIR__ . '/tests/SampleTest.php',
);
